### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by neilk17** [nandorojo/you2txt#1]
Failed to process transcripts.

Thanks for making this. I installed it on my computer ran yarn and yarn dev.
I'm getting errors when I run it.

Do I need to add any environment variables? I'm guessing Redis?

**Comment by nandorojo** [comment]
Oh yeah it expects the Vercel KV key. This shouldn't be necessary though we could make the caching optional and opt out if the env isn't set. Let me look

**Comment by nandorojo** [comment]
Fixed in the latest 2 commits, can you try pulling?
